language: php
 
php:
    - 5.6
    - 7
    - hhvm
 
matrix:
    allow_failures:
        - php: hhvm
        - php: 7
 
before_script:
    - composer self-update
    - composer install
 
script:
    - ./vendor/bin/phpunit
 
notifications:
    email: true

jdk:
  - oraclejdk8  # needed for local Neo4j 3.0+

before_install:
  - NEO4J_VERSION=3.0.1
  - wget dist.neo4j.org/neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - tar -xzf neo4j-community-$NEO4J_VERSION-unix.tar.gz
  - sed -i s/#dbms.security.auth_enabled=false/dbms.security.auth_enabled=false/g neo4j-community-$NEO4J_VERSION/conf/neo4j.conf
  - neo4j-community-$NEO4J_VERSION/bin/neo4j start
