language: php
 
php:
    - 5.6
    - 7
    - hhvm
 
matrix:
    allow_failures:
        - php: hhvm
        - php: 7
 
before_script:
    - composer self-update
    - composer install
 
script:
    - ./vendor/bin/phpunit
 
notifications:
    email: true

jdk:
  - oraclejdk7  # needed for local Neo4j 2.0+

before_install:
  - wget dist.neo4j.org/neo4j-community-2.2.0-unix.tar.gz
  - tar -xzf neo4j-community-2.2.0-unix.tar.gz
  - sed -i.bak s/dbms.security.auth_enabled=true/dbms.security.auth_enabled=false/g neo4j-community-2.2.0/conf/neo4j-server.properties
  - neo4j-community-2.2.0/bin/neo4j start
